### ISSUE TITLE
Failed to load dynamic library 'librust_ldk_node.so': dlopen failed: cannot locate symbol "ERR_lib_error_string"

### ISSUE THREAD

**Issue by vatshal** [lightningdevkit/ldk-node#286]
I am trying to use it with Flutter latest version and when I run the project on an Android device from Visual Studio code, it gives the following error to me

Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'librust_ldk_node.so': dlopen failed: cannot locate symbol "ERR_lib_error_string" referenced by "/data/app/com.example.testwallet1-P8Vg9WPhchDMRJYwSpXtag==/lib/arm64/librust_ldk_node.so"

E/flutter (11703): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/flutter (11703): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter (11703): #2      dylib (package:ldk_node/src/utils/loader.dart:10:26)
E/flutter (11703): #3      dylib (package:ldk_node/src/utils/loader.dart)
E/flutter (11703): #4      loaderApi (package:ldk_node/src/utils/loader.dart:11:45)
E/flutter (11703): #5      loaderApi (package:ldk_node/src/utils/loader.dart)
E/flutter (11703): #6      Builder.build (package:ldk_node/src/root.dart:616:25)

**Comment by vatshal** [comment]
> Do I understand correctly that you try to use the Flutter bindings? Do you mind opening this issue on the project website for the bindings?: https://github.com/LtbLightning/ldk-node-flutter

Thanks for your response, I also reported the same issue on https://github.com/LtbLightning/ldk-node-flutter

I just want to correct here that I am developing an application with the help of https://pub.dev/documentation/ldk_node/latest/ this package and it's not working with the latest flutter version 3.19.6

**Comment by vatshal** [comment]
> > > Do I understand correctly that you try to use the Flutter bindings? Do you mind opening this issue on the project website for the bindings?: https://github.com/LtbLightning/ldk-node-flutter
> > 
> > 
> > Thanks for your response, I also reported the same issue on https://github.com/LtbLightning/ldk-node-flutter
> > I just want to correct here that I am developing an application with the help of https://pub.dev/documentation/ldk_node/latest/ this package and it's not working with the latest flutter version 3.19.6
> 
> Alright, thank you very much for reporting this! As this seems to be a Flutter-specific issue, we'll need to find a solution over at said repository. Closing this issue here for now.

Thanks, hopefully, this package will be compatible with the latest flutter soon....
